Build correct URL depending on protocol (http/https)
sap-labs-france/ev-sap-smart-charging pull request #39
Opened 2021-05-26 10:37 UTC by roiko

If APIs are exposed on HTTP protocol, the requestUrl is not correctly built because "http://" has length = 7 (not 8)

2021-05-28 18:25 UTC, jerome-benoit requested changes

2021-05-28 18:25 UTC, jerome-benoit commented on SapSmartChargingIntegration.ts
> +    const protocolEnd = url.indexOf('https://') === 0 ? 8 : 7;
Could you please use the enumeration `ServerProtocol` enumeration and `startsWith()` on string?

2021-05-31 12:37 UTC, roiko commented on SapSmartChargingIntegration.ts
> +    const protocolEnd = url.indexOf('https://') === 0 ? 8 : 7;
Sure! I cannot find the where ServerProtocol enumeration is defined, can you please help me?
Thanks

2021-05-31 14:28 UTC, jerome-benoit commented on SapSmartChargingIntegration.ts
> +    const protocolEnd = url.indexOf('https://') === 0 ? 8 : 7;
It's in the ev-server main repository: `types/Server.ts`.

2021-06-01 08:34 UTC, jerome-benoit approved these changes

2021-06-01 08:35 UTC, merged